// <auto-generated />
using System;
using Infra.Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251208182529_addStatusToOrder")]
    partial class addStatusToOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EShop.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cateogries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "دسته بندی محصولات دیجیتال شامل موبایل و لبتاب",
                            IsDelete = false,
                            Title = "محصولات دیجیتال"
                        },
                        new
                        {
                            Id = 2,
                            Description = "پوشاک شامل کت وشلوار ، لباس های اسپرت",
                            IsDelete = false,
                            Title = "پوشاک"
                        },
                        new
                        {
                            Id = 3,
                            Description = "محصولات آرایشی و بهداشتی ",
                            IsDelete = false,
                            Title = "محصولات آرایشی بهداشتی"
                        });
                });

            modelBuilder.Entity("EShop.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuestId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TotalPrice")
                        .HasColumnType("bigint");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EShop.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EShop.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInSlider")
                        .HasColumnType("bit");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UnitCost")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "لباس مناسب ورزش روزانه",
                            ImagePath = "/Products/1.jpg",
                            IsDelete = false,
                            IsInSlider = true,
                            Rate = 4,
                            Stock = 15,
                            Title = "لباس ورزشی",
                            UnitCost = 350000L
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "کفش حرفه‌ای راحتی",
                            ImagePath = "/Products/2.jpg",
                            IsDelete = false,
                            IsInSlider = true,
                            Rate = 5,
                            Stock = 8,
                            Title = "کفش اسپرت",
                            UnitCost = 780000L
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "ساعت هوشمند با امکانات کامل",
                            ImagePath = "/Products/3.jpg",
                            IsDelete = false,
                            IsInSlider = true,
                            Rate = 4,
                            Stock = 5,
                            Title = "ساعت هوشمند",
                            UnitCost = 1250000L
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "کیفیت بالا و باتری مناسب",
                            ImagePath = "/Products/4.jpg",
                            IsDelete = false,
                            IsInSlider = false,
                            Rate = 3,
                            Stock = 25,
                            Title = "هندزفری بیسیم",
                            UnitCost = 420000L
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "مناسب سفر و دانشگاه",
                            ImagePath = "/Products/5.jpg",
                            IsDelete = false,
                            IsInSlider = false,
                            Rate = 4,
                            Stock = 12,
                            Title = "کوله پشتی",
                            UnitCost = 260000L
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "کیبورد RGB حرفه‌ای",
                            ImagePath = "/Products/6.jpg",
                            IsDelete = false,
                            IsInSlider = false,
                            Rate = 5,
                            Stock = 7,
                            Title = "کیبورد گیمینگ",
                            UnitCost = 690000L
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "ماوس با حساسیت بالا",
                            ImagePath = "/Products/7.jpg",
                            IsDelete = false,
                            IsInSlider = false,
                            Rate = 4,
                            Stock = 18,
                            Title = "ماوس گیمینگ",
                            UnitCost = 350000L
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "مانیتور Full HD",
                            ImagePath = "/Products/8.jpg",
                            IsDelete = false,
                            IsInSlider = false,
                            Rate = 5,
                            Stock = 4,
                            Title = "مانیتور 24 اینچ",
                            UnitCost = 3200000L
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "قابلیت شارژ سریع",
                            ImagePath = "/Products/9.jpg",
                            IsDelete = false,
                            IsInSlider = false,
                            Rate = 4,
                            Stock = 20,
                            Title = "پاوربانک",
                            UnitCost = 550000L
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "کیفیت صدای بالا",
                            ImagePath = "/Products/10.jpg",
                            IsDelete = false,
                            IsInSlider = false,
                            Rate = 5,
                            Stock = 6,
                            Title = "هدفون حرفه‌ای",
                            UnitCost = 980000L
                        });
                });

            modelBuilder.Entity("EShop.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Credit")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Credit = 100000000L,
                            FullName = "Admin",
                            IsDelete = false,
                            Password = "123",
                            Role = 1,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("EShop.Domain.Entities.UserCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("UserCartItems");
                });

            modelBuilder.Entity("EShop.Domain.Entities.Order", b =>
                {
                    b.HasOne("EShop.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("EShop.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShop.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EShop.Domain.Entities.Product", b =>
                {
                    b.HasOne("EShop.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EShop.Domain.Entities.UserCartItem", b =>
                {
                    b.HasOne("EShop.Domain.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EShop.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EShop.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EShop.Domain.Entities.Product", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("EShop.Domain.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
